### ISSUE TITLE
2 new additions since last deploy

### ISSUE THREAD

**Issue by LayZeeDK** [PetrNikolas/Awesome-Angular-Resources#2]
Hi Petr,

There has been 2 new resources added since the last deploy. When are you going to deploy with the new resources? 😊

**Comment by PetrNikolas** [comment]
Hi, your resources are deployded in production. You can try clean cache ;)

**Comment by LayZeeDK** [comment]
Thanks, I see them now without clearing cache. When were they deployed?

**Comment by PetrNikolas** [comment]
I think 2 weeks ago.

**Comment by LayZeeDK** [comment]
Alright, thank you. Everything seems to be in order.
